### PR TITLE
HPCC-29973

### PR DESCRIPTION
**Pull request by NSel1727**
Copy over the content from Attila Vamos' OBT repository to the HPCC Systems one.

### CODE REVIEW

**Comment by NSel1727** [comment]
@AttilaVamos

**Review by AttilaVamos — CHANGES_REQUESTED** [review]
Please check the first line of all Python files and fix them where needed.

**Review by AttilaVamos — APPROVED** [review]
Good for initial merge.

**Comment by AttilaVamos** [comment]
@jakesmith please check and merge.

**Comment by jakesmith** [comment]
Do we actually want OBT to be part of the community repository and not in its own repository?
That was the original idea, in fact an empty repository was created for that purpose a while back : https://github.com/hpcc-systems/OBT

@ghalliday - what's your view on this?

**Comment by ghalliday** [comment]
@AttilaVamos do you want to transfer the OBT repo to hpcc-systems instead of copying the files in one commit.  The difference is whether you retain the commit history or not.

**Comment by ghalliday** [comment]
@AttilaVamos closing because there is no response to the question.  Transferring ownership may be a better idea.

**Comment by ghalliday** [comment]
Closing

**Pull request closed without merging**
